### ISSUE TITLE
Automatically generate the MeMAD ontology and add the other used ontologies to the graph

### ISSUE THREAD

**Issue by Siliam** [MeMAD-project/rdf-converter#11]
A script to generate the MeMAD ontology.
Listing all the other used ontologies in SPARQL queries

**Comment by rtroncy** [comment]
If the idea is to generate the OWL ontology from the knowledge graph, then this is not a good idea, since the converter should take into account the ontology. I'm closing this issue, feel free to re-open it if I'm missing something.
