### ISSUE TITLE
MeMAD ontology should be versioned in this repo

### ISSUE THREAD

**Issue by rtroncy** [MeMAD-project/rdf-converter#12]
This issue is related to #11. The MeMAD ontology should be versioned in this repo.

Regarding the other ontologies being used, it may be worth to also have a local copy of them in this repo as for the current version we are using. All ontologies should naturally be loaded in the sparql endpoint.

**Comment by Siliam** [comment]
Following f6aad92, the MeMAD ontology is now included in [rdf-converter/ontology](https://github.com/MeMAD-project/rdf-converter/blob/master/ontology/memad.ttl).
