### ISSUE TITLE
Some (radio) entries have 2 types (and sometimes 2 titles)

### ISSUE THREAD

**Issue by Siliam** [MeMAD-project/rdf-converter#14]
The extra-type is due to the lack of "R" in their Archive entries, the contingent second title is due to slight differences in titling between the Archive and the Legal Deposit.

**Comment by rtroncy** [comment]
The type of the Editorial Object should rather be based on the broadcasting channel than on the presence of a R in the local ID, no?

Regarding the little differences in the title one can find between the Professional Archive or the Legal Deposit, I suggest to ask the question to INA. We could keep both, but if we use the same property, then we loose the provenance of which department provides which title.

**Comment by Siliam** [comment]
> The type of the Editorial Object should rather be based on the broadcasting channel than on the presence of a R in the local ID, no?

Updated to be based on the source channel in 44d356d1d9087fb4f83b9abc558789c06c44aeba.

**Comment by rtroncy** [comment]
So, do you keep both titles when they differ? We can find back their provenance when looking up in which graph the statement belongs to, is this the expected behavior? If so, what should a client such as the Explorer display?

**Comment by Siliam** [comment]
The issue of **types** was probably due to an old dump, as this query now returns no programs:
```
SELECT ?object ?title (count(distinct ?type) as ?n_types)
WHERE 
{ 
   ?object a ?type; 
      ebucore:title ?title;
      dct:publisher ?publisher.

   FILTER (?publisher in ('INA-PA', 'INA-LD')). 
}
GROUP BY ?object ?title
HAVING (count(distinct ?type) > 0)
```

However, an object can have multiple titles if it appears both in PA and LD, as shown [here for example](https://data.memad.eu/fit/journal-07h30/03215aeb34a82357a0bf2f7a73d6e1c3ba9d37c0).
