### ISSUE TITLE
Duration missing on Yle parts

### ISSUE THREAD

**Issue by Siliam** [MeMAD-project/rdf-converter#19]
We have the start and end metadata but the duration information is missng (e.g. https://data.memad.eu/describe/?url=http%3A%2F%2Fdata.memad.eu%2Fyle%2Fstromso%2F2909d9c5e1a1db711d273892909f14a5f8708fa2&sid=357)

**Comment by rtroncy** [comment]
True. Duration can be computed but it should be materialized in the KG.

Next, why this [particular example](http://data.memad.eu/yle/stromso/2909d9c5e1a1db711d273892909f14a5f8708fa2) has 2 different start time and 2 different end time?

**Comment by Siliam** [comment]
`ebucore:duration` added in Commit 44d356d1d9087fb4f83b9abc558789c06c44aeba. 
Example: https://data.memad.eu/yle/satuhaat/ad3daa82dff41dc4ddf279bf7d3e6485070b1dcd
