### ISSUE TITLE
Some parts are missing parents

### ISSUE THREAD

**Issue by Siliam** [MeMAD-project/rdf-converter#20]
Some parts in the dataset seem to refer to non-existing parent programs, e.g. https://data.memad.eu/fcr/fiction-feuilleton/a8e7dd62e5e0725335e5b25050ef65991de9a6b2
Check if this is the case in the data as well or a conversion bug

**Comment by Siliam** [comment]
This is due to a mismatch in the data, as this Part is supposed to fall into the "Fiction. Feuilleton" timeslot, and not to "Le Feuilleton" as per the [program data](https://data.memad.eu/fcr/le-feuilleton/c5b05409b577d5ca29a908f8318cf9b9848962a5).

**Comment by rtroncy** [comment]
Wait, the reason for the bug has been now traced but I'm not sure it is resolved. What actions did you take?

**Comment by Siliam** [comment]
I was using the "R" in the identifier to type a program either "TV" or "Radio", now I'm using the name of the channel.
