### ISSUE TITLE
Make use of Controlled Vocabularies  in the conversion

### ISSUE THREAD

**Issue by Siliam** [MeMAD-project/rdf-converter#5]
Switch from string values to controlled vocabularies URIs for some categorical fields (Roles, Genres ..)

**Comment by rtroncy** [comment]
We should list, in this issue, the exhaustive list of fields that will benefit from being linked to terms defined in a controlled vocabulary and indicate the chosen controlled vocabulary.

For the implementation, I suggest to rely on [String2Vocabulary](https://github.com/DOREMUS-ANR/string2vocabulary/)

**Comment by Siliam** [comment]
The fields concerned with this update:
- Language
- Theme
- Genre (potentially aligned with [EBU Genre CS](https://www.ebu.ch/metadata/cs/ebu_ContentGenreCS_p.xml.htm))
- Role (potentially aligned with [EBU Role CS](https://www.ebu.ch/metadata/cs/ebu_RoleCodeCS_p.xml.htm))

**Comment by Siliam** [comment]
Controlled vocabularies added in 8490dc1.
